In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd

## Prapare Data

In [190]:
df = pd.read_csv('./spambasetrain.csv', header=None)

In [191]:
train_set = df

In [192]:
train_x = df[df.columns[:9]].values

In [193]:
train_y = df[df.columns[-1]].values

## Calculate Means

In [194]:
means = np.zeros(shape=(2,9))
variances = np.zeros(shape=(2,9))
x_y_0 = (train_set.loc[train_set[9]==0])[df.columns[:9]]
x_y_1 = (train_set.loc[train_set[9]==1])[df.columns[:9]]
means[0]=(np.mean(x_y_0, axis=0));
means[1]=(np.mean(x_y_1,axis=0))

x_y_0 = x_y_0.values
x_y_1 = x_y_1.values

In [195]:
x_y_1.shape

(1205, 9)

In [196]:
(x_y_0 - means[0][None,:]).shape

(1794, 9)

In [197]:
means[0]

array([4.84258640e-02, 1.57486622e-01, 1.69598662e-02, 1.10712932e-01,
       1.15027871e-02, 2.58924192e-02, 2.37658974e+00, 1.81822742e+01,
       1.64143255e+02])

In [198]:
x_y_0[:5]

array([[0.000e+00, 3.160e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.125e+00, 2.000e+00, 9.000e+00],
       [0.000e+00, 7.350e-01, 0.000e+00, 7.350e-01, 0.000e+00, 0.000e+00,
        2.571e+00, 1.000e+01, 1.800e+01],
       [0.000e+00, 0.000e+00, 0.000e+00, 8.170e-01, 0.000e+00, 0.000e+00,
        1.857e+00, 1.500e+01, 3.900e+01],
       [0.000e+00, 0.000e+00, 0.000e+00, 2.272e+00, 0.000e+00, 0.000e+00,
        1.750e+00, 7.000e+00, 1.400e+01],
       [5.500e-02, 3.340e-01, 0.000e+00, 5.500e-02, 0.000e+00, 5.500e-02,
        1.685e+00, 6.000e+00, 5.900e+01]])

In [199]:
(x_y_0-means[0])

array([[-4.84258640e-02,  1.58513378e-01, -1.69598662e-02, ...,
        -1.25158974e+00, -1.61822742e+01, -1.55143255e+02],
       [-4.84258640e-02,  5.77513378e-01, -1.69598662e-02, ...,
         1.94410256e-01, -8.18227425e+00, -1.46143255e+02],
       [-4.84258640e-02, -1.57486622e-01, -1.69598662e-02, ...,
        -5.19589744e-01, -3.18227425e+00, -1.25143255e+02],
       ...,
       [-4.84258640e-02, -9.48662207e-03, -1.69598662e-02, ...,
        -7.07589744e-01, -3.18227425e+00,  2.28567447e+01],
       [-4.84258640e-02, -1.57486622e-01, -1.69598662e-02, ...,
        -4.39589744e-01, -3.18227425e+00, -1.02143255e+02],
       [-4.84258640e-02, -1.57486622e-01, -1.69598662e-02, ...,
         5.41410256e-01,  2.88177258e+01, -5.61432553e+01]])

In [200]:
(x_y_0-means[0])**2

array([[2.34506430e-03, 2.51264910e-02, 2.87637062e-04, ...,
        1.56647689e+00, 2.61866000e+02, 2.40694297e+04],
       [2.34506430e-03, 3.33521702e-01, 2.87637062e-04, ...,
        3.77953478e-02, 6.69496119e+01, 2.13578511e+04],
       [2.34506430e-03, 2.48020361e-02, 2.87637062e-04, ...,
        2.69973502e-01, 1.01268694e+01, 1.56608343e+04],
       ...,
       [2.34506430e-03, 8.99959984e-05, 2.87637062e-04, ...,
        5.00683245e-01, 1.01268694e+01, 5.22430778e+02],
       [2.34506430e-03, 2.48020361e-02, 2.87637062e-04, ...,
        1.93239143e-01, 1.01268694e+01, 1.04332446e+04],
       [2.34506430e-03, 2.48020361e-02, 2.87637062e-04, ...,
        2.93125066e-01, 8.30461318e+02, 3.15206512e+03]])

In [201]:
((x_y_0-means[0])**2).shape

(1794, 9)

In [202]:
np.sum((x_y_0-means[0])**2,axis=0).shape

(9,)

## Calculate Variances

In [203]:
variances[0] = (1./(len(x_y_0)-1.)) * np.sum((x_y_0-means[0])**2,axis=0)

In [204]:
variances[1] = (1./(len(x_y_1)-1.)) * np.sum((x_y_1-means[1])**2.,axis=0)

In [205]:
def gaussian(x, mu, var):
    t = np.exp(-(x - mu)**2. / (2. * var)) * 1./(np.sqrt(2*np.pi*var))
    return t

In [206]:
df_test = pd.read_csv('./spambasetest.csv',header=None)

In [207]:
test_x = df_test[df_test.columns[:9]]

In [208]:
test_x = test_x.values

In [209]:
test_x.shape

(200, 9)

In [210]:
(test_x - means[0]).shape

(200, 9)

## Calculate Likelihood

In [211]:
# def calculate_likelyhood(test_x,means,variances):
likelihood = [None,None]
likelihood[0] = gaussian(test_x,means[0],variances[0])
likelihood[1]=  gaussian(test_x,means[1],variances[1])


In [212]:
likelihood = np.asarray(likelihood)

In [170]:
np.log(likelihood[0][0])

array([ 0.28125921,  0.23270544,  1.71624736, -0.49698477,  1.81565988,
        0.2853576 , -2.73229904, -4.75025349, -6.94494544])

In [171]:
prior =[None,None]
prior[0] = train_set.loc[train_set[9]==0].shape[0]/train_set.shape[0]
prior[1] = train_set.loc[train_set[9]==1].shape[0]/train_set.shape[0]
prior = np.asarray(prior)

In [172]:
np.sum(np.log(likelihood),axis=2).shape

(2, 200)

In [173]:
prior[:,None]

array([[0.5981994],
       [0.4018006]])

In [174]:
# predict:
log_p = np.sum(np.log(likelihood),axis=2)+ prior[:,None]

In [175]:
log_p[0,0]

-9.99505387228637

In [176]:
log_p[1,0]

-15.80567910093711

In [177]:
log_p[0]<=log_p[1]

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True, False,  True,  True, False, False,  True,
        True, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True, False, False,
       False, False,  True, False, False, False,  True, False,  True,
        True, False, False, False, False, False,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False,  True, False, False,
        True,  True,

In [178]:
prediciton = (log_p[0] <= log_p[1]).astype(np.int)

In [179]:
prediciton

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [180]:
prediciton[22*8-1]

1

In [181]:
log_p.shape

(2, 200)

In [182]:
log_p[0,100]

-15.604126143138844

In [183]:
log_p[1,100]

-15.119159768482307

In [184]:
test_y = df_test[df_test.columns[9]].values

In [185]:
test_y.shape

(200,)

In [186]:
confusion_matrix = (prediciton == test_y)

In [187]:
confusion_matrix

array([ True,  True,  True,  True, False,  True, False,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True, False, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True, False,  True,  True,  True,  True,
        True,  True,

In [59]:
len([i for i in confusion_matrix if i == True])

160

In [224]:
len([i for i in test_y if i == 0])

118